apiVersion: v1
kind: Pod
metadata: 
 name: nginx
 labels:
  app: nginx
spec:
 containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort:80
    volumeMounts:
    - name: nginx-vol
      mountPath: /user/ado

  - name: bashy-container-2
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the bashy container"]
      